config/routes.rb
Rails.application.routes.draw do

  post 'contact_us/create'

  post 'live/search'

  get 'live/search'

  resources :blogs
  get 'acount/index'

  devise_for :users, :controllers => { :registrations => "my_devise/registrations" }
  resources :plantain_crops
  resources :users

  
  get "contactanos" => 'contact_us#index'
  get "better-plantain" => 'home#aboutus'
  get "plantain_crops/analisis/:id" => 'plantain_crops#crop_analysis', as: :analisis
  get "home" => 'home#index'
  post "home" => 'home#index'
  get "home/index"
  root 'home#index'

end

app/controllers/acount_controller.rb
class AcountController < ApplicationController
	
	before_action :authenticate_user!

  def index
  	@blogs = current_user.blogs.paginate(:page => params[:page], :per_page => 10)
  	@plantain_crops = current_user.plantain_crops.reorder("created_at DESC").paginate(:page => params[:page], :per_page => 3)
  end
end

app/helpers/acount_helper.rb
module AcountHelper
end

app/views/acount/_crop_data.html.erb
<style type="text/css" >
	.description{
		margin:0px !important;
	}
</style>

<div class="project">
	<h3><%= crop.name %></h3>
	<div class="divider" style="margin-top:10px;"></div>
	<div class="screen">
		
	</div>
	<p class="description" >
		Este cultivo tiene una extensión de <%= crop.size %> hectáreas y esta localizado en <%= crop.location %>.
	</p>
	<% if crop.guineo || crop.harton || crop.macho || crop.rojo || crop.valery%>
		<p class="description" >En el terreno se cultivan siguientes clases de platano:</p>
		<ul>
			<% if crop.guineo%>
			<li>Guineo</li>
			<% end %>
			<% if crop.harton%>
			<li>Hartón</li>
			<% end %>
			<% if crop.macho%>
			<li>Macho</li>
			<% end %>
			<% if crop.rojo%>
			<li>Rojo</li>
			<% end %>
			<% if crop.valery%>
			<li>Valery</li>
			<% end %>								
		</ul>
	<% else %>
		<p class="description" >Aún no se cultivan en el terreno alguna variedad de platano.</p>
	<% end %>
	<p class="description" >La calificación para este cultivo fue de: </p>
	<ul>
		<li><%= crop.score %> punto<%= 's' if crop.score != 1 %></li>
	</ul>
	<%= PlantainCropsHelper::analysis_range(crop)%>
	<div class="divider"></div>
	<div class="visit">
		<%= link_to 'Ir al análisis del cultivo', analisis_path(crop.id), {class:'button'}%>
	</div>
</div>

app/views/acount/_right_column.html.erb
<style type="text/css">

.comments{
	background:white;
	min-height: 600px;
	border-radius: 5px;
	padding: 10px;
}	

</style>

<div class="col-md-3 sidebar comments" >
	<i class="fa fa-comments-o"></i>
	<p style="display:inline">Estos son tus comentarios:</p>
  <ul>
    <% unless @blogs.empty? %>
      <% my_last_articles=@blogs %>
      <% if !my_last_articles.nil? %>
        <% for my_art in my_last_articles %>
          <li>
            <strong><%= my_art.created_at.strftime("%d %b") %></strong>
            <%= link_to my_art.title, blog_path(my_art.id) %>
          </li>
        <% end %>
      <% else %>
      <li>
        <strong> No hay artículos </strong>
      </li>                  
      <% end %> 
    <% else %>
      <p>No tienes comentarios</p>
    <% end %>
  </ul>	
</div>

app/views/acount/_your_crops.html.erb
<div >
	<% unless @plantain_crops.empty? %>
		<% for crop in @plantain_crops %>
			<%= render partial: 'crop_data', locals: {crop: crop} %>							
		<% end %>
	<% else %>
		<div class="project">
			<h3>Actualmente no haz ingresado ningún cultivo</h3>
			<div class="row">
				<div class="col-md-12">
					<div class="flexslider">
					  	<ul class="slides">
								<li>
									<%=image_tag('slider/platano01.jpg')%>
								</li>
								<li>
									<%=image_tag('slider/platano02.jpg')%>
								</li>
								<li>
									<%=image_tag('slider/platano03.jpg')%>
								</li>
								<li>
									<%=image_tag('slider/platano04.jpg')%>
								</li>	
					  	</ul>
					</div>
				</div>
			</div>
			<h3>Vamos animate a ingresar la informacion de tu cultivo y aprende a como mejorar tus practicas agropecuarias</h3>
			<div class="visit">
				<%= link_to 'ingresa un cultivo', new_plantain_crop_path, {class:'button'}%>
			</div>						
		</div>	
	<% end %>				
</div>

<script type="text/javascript">
	$( document ).ready(function() {
		$('.flexslider').flexslider({
			directionNav: false,
			slideshowSpeed: 4000
		});
		$('[data-toggle="tooltip"]').tooltip();
	});
</script>

app/views/acount/index.html.erb
<div id="showcase">
	<div class="container">
		<div class="row header">
			<div class="col-md-2">
				<div style="width:150px;">
					<img src="/images/leaf-82043_1920.jpg" class="img-responsive" />
				</div>
			</div>
			<div class="col-md-10" style="padding-left:25px;">
				<h3>Hola <%= current_user.name %></h3>
				<p>tu email: <%=current_user.email%></p>
				<p>Tienes <%=current_user.plantain_crops.size%> cultivo<%= 's' if current_user.plantain_crops.size > 1%> ingresados </p>					
			</div>			
		</div>
		<div class="row">
			<div class="col-md-9">
				<%= render partial: 'your_crops' %>
				<%= will_paginate @plantain_crops %>
			</div>
				<%= render partial: 'right_column' %>				
		</div>	
	</div>
</div>