config/routes.rb
Rails.application.routes.draw do

  post 'contact_us/create'

  post 'live/search'

  get 'live/search'

  resources :blogs
  get 'acount/index'

  devise_for :users, :controllers => { :registrations => "my_devise/registrations" }
  resources :plantain_crops
  resources :users

  
  get "contactanos" => 'contact_us#index'
  get "better-plantain" => 'home#aboutus'
  get "plantain_crops/analisis/:id" => 'plantain_crops#crop_analysis', as: :analisis
  get "home" => 'home#index'
  post "home" => 'home#index'
  get "home/index"
  root 'home#index'

end

app/models/plantain_crop.rb
class PlantainCrop < ActiveRecord::Base
	
	belongs_to :user

	validates :name, :location, :size, :town, :kind_land, :depth_range, :weather_range, 
            :planting_distance, :leaf_removal, :fungicide, :underpinned, :sheathed, 
            :finger_size, presence: true

  after_create :score_verification

  WEIGHTED_NULL = 0
  WEIGHTED_LOW 	= 1
  WEIGHTED_HALF =	3
  WEIGHTED_HIGH	= 5
  WEIGHTED_TOTAL = 50
  RANGE_LOW = [0, 17]
  RANGE_HALF = [18, 33]
  RANGE_HIGH = [34, 50]

  def self.plantains_in_crop(plantain_crop)

    kind_plantains_y = [] 
    kind_plantains_n = []
 
    if plantain_crop.guineo
      kind_plantains_y << 'Guineo'
    else
      kind_plantains_n << 'Guineo'
    end
    if plantain_crop.harton
      kind_plantains_y << 'Hartón'
    else
      kind_plantains_n << 'Hartón'
    end
    if plantain_crop.macho
      kind_plantains_y << 'Macho'
    else
      kind_plantains_n << 'Macho'
    end
    if plantain_crop.rojo
      kind_plantains_y << 'Rojo'
    else
      kind_plantains_n << 'Rojo'
    end
    if plantain_crop.valery
      kind_plantains_y << 'Valery'
    else
      kind_plantains_n << 'Valery'
    end

    return kind_plantains_y, kind_plantains_n

  end

  def ranking_verifation
    
  end

  private
  def score_verification
    
    in_crop = self
    new_score = in_crop.score
    if in_crop.guineo || in_crop.harton || in_crop.macho || in_crop.rojo || in_crop.valery
      new_score += WEIGHTED_HALF 
    end

    unless in_crop.kind_land == 'Ninguno'
      new_score += WEIGHTED_HIGH
    end

    if in_crop.depth_range == '1.2-1.5'
      new_score += WEIGHTED_LOW
    end

    if in_crop.weather_range == '22-27'
      new_score += WEIGHTED_LOW
    end

    if in_crop.has_irrigation
      new_score += WEIGHTED_HIGH
    end

    if in_crop.has_sterilization
      new_score += WEIGHTED_HIGH
    end

    if in_crop.has_weed_control
      new_score += WEIGHTED_HIGH
    end

    unless in_crop.leaf_removal == 'Ninguno'
      new_score += WEIGHTED_HALF
    end

    unless in_crop.fungicide == 'Ninguno'
      new_score += WEIGHTED_HIGH
    end

    unless in_crop.tanks_verification
      new_score += WEIGHTED_HALF
    end

    if in_crop.clusters_selecting
      new_score += WEIGHTED_HALF
    end

    if in_crop.clusters_selecting_with_instruments
      new_score += WEIGHTED_HALF
    end

    if in_crop.clusters_packing
      new_score += WEIGHTED_HALF
    end

    if in_crop.finger_size == 'mas de 10 pulgadas'
      new_score += WEIGHTED_HIGH
    end

    p '*'*200
    puts 'new_score'
    p new_score
    in_crop.score = new_score
    in_crop.save!
    puts in_crop.score

  end

end

app/controllers/plantain_crops_controller.rb
class PlantainCropsController < ApplicationController
  before_action :set_plantain_crop, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  before_action :is_user_admin, only: [:index]

  # GET /plantain_crops
  # GET /plantain_crops.json
  def index
    @plantain_crops = PlantainCrop.all
  end

  # GET /plantain_crops/1
  # GET /plantain_crops/1.json
  def show
  end

  # GET /plantain_crops/new
  def new
    @plantain_crop = PlantainCrop.new
  end

  # GET /plantain_crops/1/edit
  def edit
  end

  # POST /plantain_crops
  # POST /plantain_crops.json
  def create
    
    #@plantain_crop = PlantainCrop.new(plantain_crop_params)
    @plantain_crop = current_user.plantain_crops.create(plantain_crop_params)

    respond_to do |format|
      if @plantain_crop.save
        
        kind_plantains_y , kind_plantains_n = PlantainCrop::plantains_in_crop(@plantain_crop)
        EmailSender.analysis_crop(current_user, @plantain_crop, kind_plantains_y , kind_plantains_n).deliver

        format.html { redirect_to @plantain_crop, notice: 'El cultivo fue creado con éxito.' }
        format.json { render :show, status: :created, location: @plantain_crop }
      else
        format.html { render :new }
        format.json { render json: @plantain_crop.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /plantain_crops/1
  # PATCH/PUT /plantain_crops/1.json
  def update
    respond_to do |format|
      if @plantain_crop.update(plantain_crop_params)
        format.html { redirect_to @plantain_crop, notice: 'El cultivo se ha actualizado correctamente.' }
        format.json { render :show, status: :ok, location: @plantain_crop }
      else
        format.html { render :edit }
        format.json { render json: @plantain_crop.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /plantain_crops/1
  # DELETE /plantain_crops/1.json
  def destroy
    @plantain_crop.destroy
    respond_to do |format|
      format.html { redirect_to plantain_crops_url, notice: 'El cultivo fue destruido con éxito.' }
      format.json { head :no_content }
    end
  end

  def crop_analysis
    crop_id = params[:id]
    @plantain_crop = PlantainCrop.find(crop_id)

    kind_plantains_y , kind_plantains_n = PlantainCrop::plantains_in_crop(@plantain_crop)

    render locals: {kind_plantains_y: kind_plantains_y, kind_plantains_n: kind_plantains_n}    
  end

  private

    def is_user_admin
      unless current_user.is_admin == true
        redirect_to root_path
      end
    end

    # Use callbacks to share common setup or constraints between actions.
    def set_plantain_crop
      @plantain_crop = PlantainCrop.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def plantain_crop_params
      params.require(:plantain_crop).permit(:name, :location, :size, 
                                            :town, :guineo, :harton, 
                                            :macho, :rojo, :valery, 
                                            :kind_land, :depth_range, :weather_range, 
                                            :has_irrigation, :planting_distance, :has_sterilization, 
                                            :has_weed_control, :leaf_removal, :fungicide,
                                            :underpinned, :sheathed, :finger_size,
                                            :tanks_verification, :clusters_processing, :clusters_selecting, 
                                            :clusters_packing, :clusters_selecting_with_instruments, :score)
    end
end

app/helpers/plantain_crops_helper.rb
module PlantainCropsHelper

	public

	def self.advantages_of_cultivated_plantains(in_crop, kind_plantains_y, kind_plantains_n)
		r = []
		unless kind_plantains_y.nil?
			r << "<p><i class='fa fa-asterisk'></i> En tu terreno estas cultivando #{kind_plantains_y.size.to_s} tipo"
			r << "s" if kind_plantains_y.size >1
			r << " de platano perfectos para la región y los cuales son: </p>"
			plantain_description(kind_plantains_y, r)
		end

		if !kind_plantains_y.nil? && !kind_plantains_n.nil?
			r << '<p><i class="fa fa-asterisk"></i> Tambien te recomendamos'
			r << 'este otro tipo' if kind_plantains_n.size == 1
			r << 'estos otros tipos' if kind_plantains_n.size > 1
			r << ' de platano que puede ser una opción para otras cosechas: </p>'
			plantain_description(kind_plantains_n, r)
		end

		if kind_plantains_y.nil? && !kind_plantains_n.nil?
			r << '<p><i class="fa fa-asterisk"></i> Te recomendamos cultivar'
			r << 'este otro tipo' if kind_plantains_n.size == 1
			r << 'estos otros tipos' if kind_plantains_n.size > 1
			r << ' de platano que puede ser una opción para otras cosechas: </p>'
			plantain_description(kind_plantains_n, r)
		end		

		return r.join('').html_safe
	end

	def self.plantain_description(kind_plantains, r)

			kind_plantains.each {|kind_plantain|
			p kind_plantain
			r << case kind_plantain
			when 'Guineo'
				'<p> -Guineo: oriundo del Asia sudoriental, actualmente Brasil y Kenia 
										 lo exportan durante todo el año. El fruto mide de 8 a 10cm, 
										 de piel muy fina y con cierto sabor a manzana. </p>'
			when 'Hartón'
				'<p> -Hartón: de características excepcionales para la exportación, 
											por cumplir con todos los requisitos de calidad exigidos; presenta además ventajas comparativas 
											por ser de porte bajo, característica que lo hace ideal para zonas de vientos fuertes. </p>'
			when 'Macho'
				'<p> -Macho: También llamado banana grande o de guisar. No es muy conocido en Europa, 
											sin embargo en muchos países tropicales es un alimento básico. Se emplea verde en diversas elaboraciones culinarias, 
											como por ejemplo cocido, frito, a la plancha o en papilla, pero no se come crudo. 
											Suele ser de mayor tamaño y más anguloso que los plátanos estándar. De coloración verde, amarilla o violácea. </p>'
			when 'Rojo'
				'<p> -Rojo: Especialidad rara de ver de la parte sudoriental de Asia; se consume preferentemente 
											caliente, porque el calor acentúa las cualidades gustativas de la pulpa roja. Presenta una piel roja, rosa o con 
											mezcla de verde. </p>'
			when 'Valery'
				'<p> -Valery: Frutos grandes sabor dulce y consistente. El nombre está registrado como marca. </p>'										 									 										 										 
			else
				''
			end
		}
		return r
	end

	def self.advantages_of_kind_land(in_crop)
		r = []
		if in_crop.kind_land == 'Ninguno'
			r << '<p><i class="fa fa-asterisk"></i> Los suelos aptos para el desarrollo del cultivo del plátano son aquellos 
						ue presentan una textura franco arenosa, franco arcillosa, franco arcillo limosa 
						y franco limosa, debiendo ser, además, fértiles y permeables. </p>'
		else
			r << '<p><i class="fa fa-asterisk"></i> El suelo de tu terreno es apto para el cultivo del platano. </p'
		end
		return r.join('').html_safe
	end

	def self.analysis_depth_range(in_crop)
		r = []
		if in_crop.depth_range == '1.2-1.5'
			r << '<p><i class="fa fa-asterisk"></i> Tu terreno tiene la profundidad adecuada. </p>'
		else
			r << '<p><i class="fa fa-asterisk"></i> Tu terreno no tiene la profundidad adecuada. </p>'
		end
		return r.join('').html_safe
	end

	def self.analysis_weather_range(in_crop)
		r = []
		if in_crop.weather_range == '22-27'
			r << '<p><i class="fa fa-asterisk"></i> El rango de temperatura para tu cultivo es el adecuado. </p>'
		else
			r << '<p><i class="fa fa-asterisk"></i> El rango de temperatura para tu cultivo no es el adecuado. 
						El plátano exige un clima cálido y una constante humedad en el aire. 
						Necesita una temperatura media de 26-27 ºC, con lluvias prolongadas y regularmente 
						distribuidas</p>'
		end
		return r.join('').html_safe		
	end

	def self.analysis_has_irrigation(in_crop)
		r = []
		if in_crop.has_irrigation
			r << '<p><i class="fa fa-asterisk"></i> Tu cultivo si posee irrigación adecuada y esto ayuda a la calidad de tu producto. </p>'
		else
			r << '<p><i class="fa fa-asterisk"></i> Los plátanos requieren mucha agua, pero corren el 
						riesgo de podrirse si el agua no se drena adecuadamente, le recomendamos implementar 
						un sistema de drenaje adecuado.</p>'
		end
		return r.join('').html_safe		
	end

	def self.analysis_has_sterilization(in_crop)
		r = []
		if in_crop.has_sterilization
			r << '<p><i class="fa fa-asterisk"></i> Si se esteriliza la semilla ó rizoma. </p>'
		else
			r << '<p><i class="fa fa-asterisk"></i> La Semilla (rizoma), debe ser pelada, eliminando la tierra adherida a ella, 
						raíces y todo tejido dañado por picudo u otros insectos. Una vez limpia, debe ser desinfectada para que quede 
						libre de patógenos.
						Se le debe hacer una inmersión de la semilla por 5-10 minutos en una mezcla de insecticida- fungicida.</p>'
		end
		return r.join('').html_safe		
	end

	def self.analysis_has_weed_control(in_crop)
		r = []
		if in_crop.has_weed_control
			r << '<p><i class="fa fa-asterisk"></i> En tu cultivo se realiza un control de plagas adecuado y esto ayuda a la calidad de tu producto. </p>'
		else
			r << '<p><i class="fa fa-asterisk"></i> Las malezas compiten con el cultivo por agua, luz y nutrientes, 
						además muchas son hospederas de enfermedades e insectos plagas. El manejo de las 
						malezas se debe realizar mediante la integración de métodos culturales, mecánicos 
						y químicos. Su efectividad dependerá de la oportunidad y eficiencia con que se 
						realicen.</p>'
		end
		return r.join('').html_safe		
	end

	def self.analysis_leaf_removal(in_crop)
		r = []
		if in_crop.leaf_removal == 'Ninguno'
			r << '<p><i class="fa fa-asterisk"></i> El deshoje tiene como objetivo la eliminación de hojas dobladas, 
						maduras e infectadas por sigatoka. Se tienen entonces dos tipos de deshoje: el de sanidad, 
						que remueve hojas no funcionales bien sea por culminación de su ciclo, daños mecánicos o por enfermedad (S. negra) 
						y el de protección del racimo, que consiste en eliminar las hojas o partes de ella que pegan al racimo produciéndole 
						cicatrización. </p>'
		else
			r << '<p><i class="fa fa-asterisk"></i> Utilizas el deshoje en tu cultivo, es una buena práctica para la calidad de tu producto. </p'
		end
		return r.join('').html_safe
	end

	def self.analysis_fungicide(in_crop)
		r = []
		if in_crop.fungicide == 'Ninguno'
			r << "<p><i class='fa fa-asterisk'></i> Debes utilizar un fungicida para mejorar la calidad de tu cultivo. 
						La siguiente tabla te muesta algunos de ellos: </p>
						<img src='#{SiteAdmin::K_SITE_ADDRESS}/images/fungicidas.jpg' class='img-responsive'>"

		else
			r << '<p><i class="fa fa-asterisk"></i> Utilizas un fungicida en tu cultivo, es una buena práctica para la calidad de tu producto. </p'
		end
		return r.join('').html_safe
	end

	def self.analysis_tanks_verification(in_crop)
		r = []
		unless in_crop.tanks_verification
			r << '<p><i class="fa fa-asterisk"></i> Antes de iniciar el corte verifique que los tanques de la empacadora 
					estén listos con agua-alumbre y agua - merteck. </p>'

		else
			r << '<p><i class="fa fa-asterisk"></i> La verificación de los tanques de la empacadora 
					estén listos con agua-alumbre y agua - merteck es una buena práctica para la calidad de tu producto. </p'
		end
		return r.join('').html_safe
	end

	def self.analysis_clusters_selecting(in_crop)
		r = []
		unless in_crop.clusters_selecting
			r << '<p><i class="fa fa-asterisk"></i> No procese racimos de plantas con menos de siete hojas funcionales. </p>'

		else
			r << '<p><i class="fa fa-asterisk"></i> El no procesar racimos de plantas con menos de siete hojas funcionales es 
						una buena práctica para la calidad de tu producto. </p'
		end
		return r.join('').html_safe
	end

	def self.analysis_clusters_selecting_with_instruments(in_crop)
		r = []
		if in_crop.clusters_selecting_with_instruments
			r << '<p><i class="fa fa-asterisk"></i> Seleccionar la fruta con calibrador y cinta métrica es 
						una buena práctica para la calidad de tu producto. </p>'

		else
			r << '<p><i class="fa fa-asterisk"></i> Seleccione la fruta con calibrador y cinta métrica para mejorar la calidad de su producto. </p'
		end
		return r.join('').html_safe
	end

	def self.analysis_clusters_packing(in_crop)
		r = []
		unless in_crop.clusters_packing
			r << '<p><i class="fa fa-asterisk"></i> No empaque coronas desgarradas, Desmane por debajo de la línea oscura que une 
						los dedos con el vástago, procurando que los plátanos caigan sueltos al tanque. Con este corte se obtienen coronas rectas 
						y limpias. </p>'

		else
			r << '<p><i class="fa fa-asterisk"></i> El no empacar coronas desgarradas es una buena practica para la calidad de su producto. </p'
		end
		return r.join('').html_safe
	end

	def self.analysis_finger_size(in_crop)
		r = []
		if in_crop.finger_size == 'mas de 10 pulgadas'
			r << '<p><i class="fa fa-asterisk"></i> Cosechar dedos de mas de 10 pulgadas es una buena practica para la calidad de su producto. </p>'
		else
			r << '<p><i class="fa fa-asterisk"></i> Cada dedo debe medir mínimo 10 pulgadas de pulpa a punta 
						y debe tener de 22 a 28 líneas de vitola. </p>'
		end
		return r.join('').html_safe
	end

	def self.analysis_range(in_crop)

		range_low = PlantainCrop::RANGE_LOW
		range_half = PlantainCrop::RANGE_HALF
		range_high = PlantainCrop::RANGE_HIGH
		score = in_crop.score		
		r = []

		r << case score
		when range_low.first..range_low.last

app/views/plantain_crops/edit.html.erb
<div class="container">
	<div class="row header">
		<div class="col-md-12">
			<h1>Editando el cultivo <%= @plantain_crop.name %></h1>
		</div>
	</div>
	<div class="row">
		<div class="col-md-12">
			<%= render 'form' %>
			</br>
			<%= link_to 'Volver a tu perfil', acount_index_path %>
		</div>
	</div>
</div>

app/views/plantain_crops/index.html.erb
<%= our_notice_alert(notice) %>

<h1>Listing Plantain Crops</h1>

<table>
  <thead>
    <tr>
      <th>Nanme</th>
      <th>Location</th>
      <th>Size</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @plantain_crops.each do |plantain_crop| %>
      <tr>
        <td><%= plantain_crop.name %></td>
        <td><%= plantain_crop.location %></td>
        <td><%= plantain_crop.size %></td>
        <td><%= link_to 'Show', plantain_crop %></td>
        <td><%= link_to 'Edit', edit_plantain_crop_path(plantain_crop) %></td>
        <td><%= link_to 'Destroy', plantain_crop, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Plantain crop', new_plantain_crop_path %>

app/views/plantain_crops/show.html.erb
<div id="status">
	<div id="update">
		<div class="container">
			<%= our_notice_alert(notice) %>
			<div class="row header">
				<div class="col-md-12">
					<div class="current-status">	
						<h2>
							<%= @plantain_crop.name %>
						</h2>
						<i class="fa fa-pencil-square-o"></i>
						<%= link_to 'Edita los datos del cultivo', edit_plantain_crop_path(@plantain_crop) %> | 
						<i class="fa fa-cogs"></i>
						<%= link_to 'Ir al análisis del cultivo', analisis_path(@plantain_crop)%>
					</div>
				</div> 
			</div>
		  <div class="page-header">
		    <h4>Datos Generales</h4>
		  </div>  				
			<div class="row row-centered">
				<div class="col-md-6 col-centered">
					<div class="panel panel-default modules">
						<ul class="list-group">
							<li class="list-group-item">
								<h4><strong>Ubicado en el municipio de:</strong></h4>
								<div style="text-align: center;">
									<h4><%= Town.find(@plantain_crop.town.to_i).name %></h4>
								</div>
							</li>
							<li class="list-group-item">
								<h4><strong>Puntuacion del cultivo:</strong></h4>
								<div style="text-align: center;">
									<h4><%= @plantain_crop.score %> punto<%= 's' if @plantain_crop.score != 1 %></h4>
								</div>
							</li>							
						</ul>
					</div>
				</div>
				<div class="col-md-6 col-centered">
					<div class="panel panel-default modules">
						<ul class="list-group">
							<li class="list-group-item">
								<h4><strong>Localización:</strong></h4>
								<div style="text-align: center;">
									<h4><%= @plantain_crop.location %></h4>
								</div>
							</li>
							<li class="list-group-item">
								<h4><strong>Tamaño del terreno:</strong></h4>
								<div style="text-align: center;">
									<h4><%= @plantain_crop.size %>ha</h4>
								</div>
							</li>
						</ul>
					</div>
				</div>
			</div>
		  <div class="page-header">
		    <h4>Datos del cultivo y el terreno</h4>
		  </div>
			<div class="row row-centered">
				<div class="col-md-6 col-centered">
					<div class="panel panel-default modules">
						<ul class="list-group">
							<li class="list-group-item">
								<h4><strong>Tipos de platanos que se siembran:</strong></h4>
								<%if @plantain_crop.guineo%>
									<div style="text-align: center;">
										<h4>Guineo</h4>
									</div>
								<% end %>
								<%if @plantain_crop.harton%>
									<div style="text-align: center;">
										<h4>Hartón</h4>
									</div>
								<% end %>
								<%if @plantain_crop.macho%>
									<div style="text-align: center;">
										<h4>Macho</h4>
									</div>
								<% end %>
								<%if @plantain_crop.rojo%>
									<div style="text-align: center;">
										<h4>Rojo</h4>
									</div>
								<% end %>
								<%if @plantain_crop.valery%>
									<div style="text-align: center;">
										<h4>Valery</h4>
									</div>
								<% end %>											
							</li>								
							<li class="list-group-item">
								<h4><strong>Textura del terreno:</strong></h4>
								<div style="text-align: center;">
									<h4><%= @plantain_crop.kind_land %></h4>
								</div>
							</li>
							<li class="list-group-item">
								<h4><strong>Profundidad del terreno:</strong></h4>
								<div style="text-align: center;">
									<h4><%= @plantain_crop.depth_range %> mts</h4>
								</div>
							</li>
							<li class="list-group-item">
								<h4><strong>Promedio de la temperatura del sitio:</strong></h4>
								<div style="text-align: center;">
									<h4><%= @plantain_crop.weather_range %> grados celsius</h4>
								</div>
							</li>
							<li class="list-group-item">
								<h4><strong>Irrigación en el sitio:</strong></h4>
								<% if @plantain_crop.has_irrigation %>
									<div style="text-align: center;">
										<h4> Si posee irrigación adecuada</h4>
									</div>
								<% else %>
									<div style="text-align: center;">
										<h4> No posee irrigación adecuada</h4>
									</div>									
								<% end %>
							</li>																					
						</ul>
					</div>
				</div>
				<div class="col-md-6 col-centered">
					<div class="panel panel-default modules">
						<ul class="list-group">
							<li class="list-group-item">
								<h4><strong>Esterilizado de la semilla ó rizoma con una mezcla de insecticida - fungicida:</strong></h4>
								<% if @plantain_crop.has_sterilization %>
								<div style="text-align: center;">
									<h4>Si se esteriliza la semilla ó rizoma</h4>
								</div>
								<% else %>
									<div style="text-align: center;">
										<h4>No se esteriliza la semilla ó rizoma</h4>
									</div>									
								<% end %>
							</li>
							<li class="list-group-item">
								<h4><strong>Control de plagas:</strong></h4>
								<% if @plantain_crop.has_weed_control %>
									<div style="text-align: center;">
										<h4>Se realiza un control de plagas adecuado</h4>
									</div>
								<% else %>
									<div style="text-align: center;">
										<h4>No se realiza un control de plagas adecuado</h4>
									</div>									
								<% end %>
							</li>
							<li class="list-group-item">
								<h4><strong>Tipo de deshoje:</strong></h4>
								<div style="text-align: center;">
									<h4><%= @plantain_crop.leaf_removal %></h4>
								</div>
							</li>
							<li class="list-group-item">
								<h4><strong>Cual fungicida se usa en su cultivo:</strong></h4>
								<div style="text-align: center;">
									<h4><%= @plantain_crop.fungicide %></h4>
								</div>
							</li>
							<li class="list-group-item">
								<h4><strong>Distancia a la que se realiza la siembra:</strong></h4>
								<div style="text-align: center;">
									<h4><%= @plantain_crop.planting_distance %> mts</h4>
								</div>
							</li>																							
						</ul>
					</div>
				</div>
			</div>
		  <div class="page-header">
		    <h4>Datos de la cosecha</h4>
		  </div>
			<div class="row row-centered">
				<div class="col-md-6 col-centered">
					<div class="panel panel-default modules">
						<ul class="list-group">
							<li class="list-group-item">
								<h4><strong>Se verífica que los tanques de la empacadora estén listos con agua-alumbre y agua - merteck, antes de iniciar el corte</strong></h4>
								<%if @plantain_crop.tanks_verification%>
									<div style="text-align: center;">
										<h4>No se verifican los tanques</h4>
									</div>
								<% else %>
									<div style="text-align: center;">
										<h4>Si se verifican los tanques</h4>
									</div>										
								<% end %>																																			
							</li>								
							<li class="list-group-item">
								<h4><strong>Se desechan los racimos maduros, gruesos, con excesivas cicatrices o maltratados</strong></h4>
								<%if @plantain_crop.clusters_selecting%>
									<div style="text-align: center;">
										<h4>Si se desechan los racimos</h4>
									</div>
								<% else %>
									<div style="text-align: center;">
										<h4>No se desechan los racimos</h4>
									</div>										
								<% end %>	
							</li>
							<li class="list-group-item">
								<h4><strong>Se selecciona la fruta con calibrador y cinta métrica:</strong></h4>
								<%if @plantain_crop.clusters_selecting_with_instruments%>
									<div style="text-align: center;">
										<h4>Si se usan instrumentos de medición</h4>
									</div>
								<% else %>
									<div style="text-align: center;">
										<h4>No se usan instrumentos de medición</h4>
									</div>										
								<% end %>	
							</li>																				
						</ul>
					</div>
				</div>
				<div class="col-md-6 col-centered">
					<div class="panel panel-default modules">
						<ul class="list-group">
							<li class="list-group-item">
								<h4><strong>Se procesa racimos de plantas con menos de siete hojas funcionales</strong></h4>
								<%if @plantain_crop.clusters_processing%>
									<div style="text-align: center;">
										<h4>No se procesan estos racimos</h4>
									</div>
								<% else %>
									<div style="text-align: center;">
										<h4>Si se procesan estos racimos</h4>
									</div>
								<% end %>	
							</li>
							<li class="list-group-item">
								<h4><strong>Empacá coronas desgarradas o curvas:</strong></h4>
								<% if @plantain_crop.clusters_packing %>
									<div style="text-align: center;">
										<h4>Se empacan estas coronas</h4>
									</div>
								<% else %>
									<div style="text-align: center;">
										<h4>No se empacan estas coronas</h4>
									</div>									
								<% end %>
							</li>
							<li class="list-group-item">
								<h4><strong>Tamaño minimo un dedo de un racimo</strong></h4>
								<div style="text-align: center;">
									<h4><%= @plantain_crop.finger_size %></h4>
								</div>
							</li>																						
						</ul>
					</div>
				</div>
			</div>			  							  				
		</div>
	</div>
</div>