config/routes.rb
Rails.application.routes.draw do

  post 'contact_us/create'

  post 'live/search'

  get 'live/search'

  resources :blogs
  get 'acount/index'

  devise_for :users, :controllers => { :registrations => "my_devise/registrations" }
  resources :plantain_crops
  resources :users

  
  get "contactanos" => 'contact_us#index'
  get "better-plantain" => 'home#aboutus'
  get "plantain_crops/analisis/:id" => 'plantain_crops#crop_analysis', as: :analisis
  get "home" => 'home#index'
  post "home" => 'home#index'
  get "home/index"
  root 'home#index'

end

app/views/layouts/_acount_header.html.erb
<header class="navbar navbar-inverse normal" role="banner">
  <div class="container">
    <div class="navbar-header">
      <button class="navbar-toggle" type="button" data-toggle="collapse" data-target=".bs-navbar-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a href="<%= root_path %>" class="navbar-brand">Better plantain</a>
    </div>
    <%= render partial: 'layouts/nav_bar'%>
  </div>
</header>

app/views/layouts/_footer.html.erb
<style type="text/css">
  #footer .copyright{text-align: center;}
  #footer .panel {background-color:transparent; padding-left: 100px;} 
  #footer .bottom-box {color: white;}
  #footer .bottom-box p {font-size: 130%; color: #eeeeee; float: left;} 
  #footer .bottom-box ul {padding: 0px;}
  #footer .bottom-box li {font-size: 15px;} 
  #footer .bottom-box .bottom-title {display: table; width: 100%;}
  #footer .bottom-box .bottom-title button {display: none; background-color: transparent;
    background-image: none; border: 1px solid transparent;}
    #footer .border-shadow {border-right: 1px solid rgba(0,0,0,0.35);
      box-shadow: 1px 0px 0 rgba(255,255,255,0.07);}
      @media (max-width: 991px){
        #footer .bottom-box .bottom-title button {display: block; float: right;}
        #footer .border-shadow {border-right: 0px solid rgba(0,0,0,0.35); border-bottom: 1px solid rgba(0,0,0,0.35);
          box-shadow: 0px 1px 0 rgba(255,255,255,0.07);}
        }
        @media (min-width: 992px) {
          #footer .bottom-box ul {display: block; height: auto !important;}
        }
        /* centered columns styles */
        .row-centered {
          text-align:center;
        }
        .col-centered {
          display:inline-block;
          float:none;
          /* reset the text-align */
          text-align:left;
          /* inline-block space fix */
          margin-right:-4px;
        }
        .col-fixed {
          /* custom width */
          width:320px;
        }
        .col-min {
          /* custom min width */
          min-width:320px;
        }
        .col-max {
          /* custom max width */
          max-width:320px;
        }


        /* centering styles for jsbin */
        html,
        body {
          width:100%;
          height:100%;
        }
        html {
          display:table;
        }
        body {
          display:table-cell;
          vertical-align:middle;
        }        
      </style>

<div id="footer">
  <div class="container">
    <div class="row row-centered panel-group" id="accordion">
      <div class="menu bottom-box border-shadow col-md-3 col-centered col-fixed panel">
        <div class="bottom-title">
          <p> Generalidades </p>
          <button class="fa fa-chevron-down" type="button" data-toggle="collapse" data-parent="#accordion" data-target=".list_generalidades"></button>
        </div>
        <ul class="list_generalidades list-unstyled collapse">
          <li><a href="<%= better_plantain_path %>">Quienes somos</a></li>
          <li><a href="<%= blogs_path %>">Blog</a></li>
          <li><a href="<%= contactanos_path %>">Contactanos</a></li>
        </ul>        
      </div>
      <div class="menu bottom-box col-md-3 col-centered col-fixed panel">
        <div class="bottom-title">
          <p> Social </p>
          <button class="fa fa-chevron-down" type="button" data-toggle="collapse" data-parent="#accordion" data-target=".list_votre_compte"></button>
        </div>
        <ul class="list_votre_compte list-unstyled collapse">
          <li><a href="https://www.youtube.com/channel/UCefiQnhKMwmgtqVoPIKybJw">Youtube</a></li>
          <li><a href="https://www.facebook.com/betterplantain2016">Facebook</a></li>
          <li><a href="https://twitter.com/better_plantain">Twitter</a></li>        
        </ul>      
      </div>           
    </div>
    <div class="row row-centered"></div>
    <div class="row row-centered copyright">
      <div class="col-md-12">
        Copyright © 2015
      </div>
    </div>
  </div>
</div>

app/views/layouts/_nav_bar.html.erb
<nav class="collapse navbar-collapse bs-navbar-collapse" role="navigation">
  <ul class="nav navbar-nav">
    <li>
      <a href="<%= root_path %>" >
        Home
      </a>
    </li>
    <li>
      <a href="<%=acount_index_path%>" >
        Perfil
      </a>
    </li>
    <li>
      <a href="#" class="dropdown-toggle" data-toggle="dropdown">
        Cultivos <b class="caret"></b>
      </a>
      <ul class="dropdown-menu">
        <li><a href="<%= new_plantain_crop_path%>">Crear un cultivo</a></li>
        <% crops = current_user.plantain_crops %>
        <% unless crops.empty? %>
          <% for crop in crops %>
            <% unless crop.id.nil? %>
              <li><%= link_to crop.name, plantain_crop_path(crop.id)%></li>
            <% end %>
          <% end %>
        <% end %>
      </ul>
    </li>
    <li>
      <%= link_to :Blog, blogs_path %>
    </li>
  </ul>
  <ul class="nav navbar-nav navbar-right">
    <li>
      <%= link_to "Cerrar Sesión", destroy_user_session_path, {:method => :delete, :class => "button-outline"} %>
    </li>
  </ul>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html class="bg">
  <head>
    <title>Better plantain</title>
    <%= favicon_link_tag 'favicon.ico' %>
    <!-- stylesheets -->
    <%= stylesheet_link_tag  'application', media: 'all', 'data-turbolinks-track' => true %>  
    <%= stylesheet_link_tag 'css/compiled/theme.css', {:media => 'all'} %>
    <%= stylesheet_link_tag 'css/vendor/animate.css', {:media => 'all'} %>
    <%= stylesheet_link_tag 'css/vendor/font-awesome.css', {:media => 'all'} %>
    <%= stylesheet_link_tag 'css/vendor/icomoon.css', {:media => 'all'} %>
    <%= stylesheet_link_tag 'css/SocialShare.css', {:media => 'all'} %>
    <%= stylesheet_link_tag 'css/general.css', {:media => 'all'} %>
    <%= stylesheet_link_tag 'css/vendor/flexslider.css', {:media => 'all'} %>

    <!-- javascript -->
    <script src="//code.jquery.com/jquery-1.10.2.js"></script>
    <script src="//code.jquery.com/ui/1.11.4/jquery-ui.js"></script>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'js/bootstrap/bootstrap.min.js' %>
    <%= javascript_include_tag('js/SocialShare.js') %>
    <%= javascript_include_tag 'js/theme.js' %>
    <%= javascript_include_tag 'js/vendor/jquery.flexslider.min.js' %>  
    <%= csrf_meta_tags %>
  </head>
  <body id="portfolio">

    <%= render partial: 'layouts/acount_header'%>

    <%= yield %>

    <%= render partial: 'layouts/footer' %>
    
  </body>
</html>

app/views/layouts/devise.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Better plantain</title>

    <!-- stylesheets -->
    <%= stylesheet_link_tag  'application', media: 'all', 'data-turbolinks-track' => true %>  
    <%= stylesheet_link_tag 'css/compiled/theme.css', {:media => 'all'} %>
    <%= stylesheet_link_tag 'css/vendor/animate.css', {:media => 'all'} %>
    <%= stylesheet_link_tag 'css/vendor/font-awesome.css', {:media => 'all'} %>
    <%= stylesheet_link_tag 'css/vendor/icomoon.css', {:media => 'all'} %>
    <%= stylesheet_link_tag 'css/SocialShare.css', {:media => 'all'} %>
    <%= stylesheet_link_tag 'css/general.css', {:media => 'all'} %>

    <!-- javascript -->
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js"></script>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'js/bootstrap/bootstrap.min.js' %>
    <%= javascript_include_tag 'js/theme.js' %>
    <%= csrf_meta_tags %>
  </head>
  <body>

    <% flash.each do |name, msg| %>
      <%= content_tag :div, msg, { id: "flash_#{name}", style: 'background-color: whitesmoke;font-size: large;text-align: center;'} %>
    <% end %>

    <%= yield %>
    
  </body>
</html>

app/views/layouts/home.html.erb
<!DOCTYPE html>
<html>
  <head>
  <meta charset="UTF-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" /> 
  <title>Better plantain</title>
  <%= favicon_link_tag 'favicon.ico' %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
      <![endif]-->

    <!-- stylesheets -->
    <%= stylesheet_link_tag  'application', media: 'all', 'data-turbolinks-track' => true %>  
    <%= stylesheet_link_tag 'css/compiled/theme.css', {:media => 'all'} %>
    <%= stylesheet_link_tag 'css/vendor/animate.css', {:media => 'all'} %>
    <%= stylesheet_link_tag 'css/vendor/font-awesome.css', {:media => 'all'} %>
    <%= stylesheet_link_tag 'css/vendor/icomoon.css', {:media => 'all'} %>
    <%= stylesheet_link_tag 'css/SocialShare.css', {:media => 'all'} %>
    <%= stylesheet_link_tag 'css/vendor/flexslider.css', {:media => 'all'} %>    
    <%= stylesheet_link_tag 'css/general.css', {:media => 'all'} %>

    <!-- javascript -->
    <script src="//code.jquery.com/jquery-1.10.2.js"></script>
    <script src="//code.jquery.com/ui/1.11.4/jquery-ui.js"></script>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'js/vendor/jquery.flexslider.min.js' %> 
    <%= javascript_include_tag 'js/bootstrap/bootstrap.min.js' %>    
    <%= javascript_include_tag('js/SocialShare.js') %>
    <%= javascript_include_tag 'js/theme.js' %>
    <%= csrf_meta_tags %>
  </head>

    <body id="home">

    <%= render partial: 'home/header' %>
    
    <%= yield %>

    <%= render partial: 'home/footer' %>

  </body>
</html>

app/views/layouts/home2.html.erb
<!DOCTYPE html>
<html>
  <head>
  <meta charset="UTF-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" /> 
  <title>Better plantain</title>
  <%= favicon_link_tag 'favicon.ico' %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
      <![endif]-->

    <!-- stylesheets -->
    <%= stylesheet_link_tag  'application', media: 'all', 'data-turbolinks-track' => true %>  
    <%= stylesheet_link_tag 'css/compiled/theme.css', {:media => 'all'} %>
    <%= stylesheet_link_tag 'css/vendor/animate.css', {:media => 'all'} %>
    <%= stylesheet_link_tag 'css/vendor/font-awesome.css', {:media => 'all'} %>
    <%= stylesheet_link_tag 'css/vendor/icomoon.css', {:media => 'all'} %>
    <%= stylesheet_link_tag 'css/SocialShare.css', {:media => 'all'} %>
    <%= stylesheet_link_tag 'css/general.css', {:media => 'all'} %>
    <%= stylesheet_link_tag 'css/vendor/flexslider.css', {:media => 'all'} %>    
    <%= stylesheet_link_tag 'css/vendor/flexslider.css', {:media => 'all'} %>

    <!-- javascript -->
    <script src="//code.jquery.com/jquery-1.10.2.js"></script>
    <script src="//code.jquery.com/ui/1.11.4/jquery-ui.js"></script>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>   
    <%= javascript_include_tag 'js/vendor/jquery.flexslider.min.js' %>
    <%= javascript_include_tag 'js/bootstrap/bootstrap.min.js' %>    
    <%= javascript_include_tag('js/SocialShare.js') %>
    <%= javascript_include_tag 'js/theme.js' %>  
    <%= csrf_meta_tags %>
  </head>

    <body id="home">

    <%= render partial: 'home/header2' %>
    
    <%= yield %>

    <%= render partial: 'home/footer' %>

  </body>
</html>